openedx/openedx-app-ios

Core/Core/CorePersistence.swift
Course/Course/CoursePersistence.swift
Dashboard/Dashboard/DashboardPersistence.swift
Discovery/Discovery/DiscoveryPersistence.swift

by adding new rules to persistentContainers

CoreData fix migrations issues

---

Core/Core/View/Base/WebBrowser.swift
Core/Core/View/Base/WebUnitView.swift
Core/Core/View/Base/WebUnitViewModel.swift
Core/Core/View/Base/WebView.swift
NewEdX/DI/ScreenAssembly.swift

Added ability to open external links from webView

Open external links in the browser

---

Core/Core.xcodeproj/project.pbxproj
Core/Core/Data/Model/Data_Discovery.swift
Core/Core/Domain/Model/Pagination.swift
Discussion/Discussion/Data/Model/Data_CommentsResponse.swift
Discussion/Discussion/Data/Network/DiscussionRepository.swift
Discussion/Discussion/Domain/DiscussionInteractor.swift
Discussion/Discussion/Presentation/Comments/Base/BaseResponsesViewModel.swift
Discussion/Discussion/Presentation/Comments/Responses/ResponsesView.swift
Discussion/Discussion/Presentation/Comments/Responses/ResponsesViewModel.swift
Discussion/Discussion/Presentation/Comments/Thread/ThreadView.swift
Discussion/Discussion/Presentation/Comments/Thread/ThreadViewModel.swift

Fix Discussion incorrect replies count

Fix Discussion incorrect replies count

---

Dashboard/Dashboard/Presentation/DashboardView.swift
Dashboard/Dashboard/Presentation/DashboardViewModel.swift

Fix an issue where an EmptyStateView was always displayed on a DashboardView.

Fix dashboard empty state

---

Podfile
Podfile.lock

Updated SwiftLint pod version to 0.5
Updated SwiftGen pod version to  6.6
Updated Alamofire pod version to 5.7
Updated Introspect pod version to 0.6
Updated Kingfisher pod version to 7.8
Updated Swinject pod version to 2.8.3
These changes were made to ensure that the project's dependencies are up to date and compatible with the latest versions.

Updated pod versions for NewEdX and Core targets.

---

Core/Core/View/Base/FlexibleKeyboardInputView.swift
Core/Core/View/Base/PickerMenu.swift
Discussion/Discussion/Presentation/Comments/Responses/ResponsesView.swift
Discussion/Discussion/Presentation/Comments/Thread/ThreadView.swift

fix PickerMenu issues

---

OpenEdX.xcodeproj/project.pbxproj

Fixed FirebaseCrashlytics upload dSYM issue on Archive build.

Fix issue with ShellScript for FirebaseCrashlytics.

---

Discussion/Discussion/Presentation/Comments/Responses/ResponsesView.swift

MBS-86 Discussions. First comment for the answer are displayed as another answer

---

Course/Course/Presentation/Unit/CourseUnitView.swift

The encoded video player was resetting its state during screen rotation. Fixed.

encoded video dissmiss by device rotation

---

Core/Core/Configuration/Config.swift
Core/Core/Data/Repository/AuthRepository.swift
Core/Core/Network/AuthEndpoint.swift
Core/Core/Network/RequestInterceptor.swift

By default, access tokens are now in JWT format.
The type of access token can be changed in the [Core.Config](https://github.com/openedx/openedx-app-ios/blob/feature/add_support_for_jwt_tokens/Core/Core/Configuration/Config.swift) class.
Supported token types are represented by the [TokenType](https://github.com/openedx/openedx-app-ios/blob/feature/add_support_for_jwt_tokens/Core/Core/Configuration/Config.swift#L36) enum.
```
enum TokenType: String {
case jwt = "JWT"
case bearer = "BEARER"
}
```

Added support of JWT tokens.

---

Authorization/AuthorizationTests/AuthorizationMock.generated.swift
Authorization/Mockfile
Course/CourseTests/CourseMock.generated.swift
Course/Mockfile
Dashboard/DashboardTests/DashboardMock.generated.swift
Dashboard/Mockfile
Discovery/DiscoveryTests/DiscoveryMock.generated.swift
Discovery/Mockfile
Discussion/DiscussionTests/DiscussionMock.generated.swift
Discussion/Mockfile
MockTemplate.swifttemplate
Profile/Mockfile
Profile/ProfileTests/ProfileMock.generated.swift
WhatsNew/Mockfile
WhatsNew/WhatsNewTests/WhatsNewMock.generated.swift

[SwiftyMocky](https://github.com/MakeAWishFoundation/SwiftyMocky) library is using the 1.8.8 version of [Sourcery](https://github.com/krzysztofzablocki/Sourcery). [SwiftyMocky](https://github.com/MakeAWishFoundation/SwiftyMocky) was last updated on August 21, 2022, but meanwhile, other versions of [Sourcery](https://github.com/krzysztofzablocki/Sourcery) were released, and the current version is 2.1.2.
The default version (1.8.8) of Sourcery with SwiftyMocky is not generating test files on Mac chips and results in an error.
I've updated the Sourcery version to the latest version `2.1.2`
[Ticket](https://github.com/orgs/openedx/projects/56/views/7?pane=issue&itemId=43307592)

chore: update Sourcery version for SwiftyMocky

---

Course/Course/Presentation/Video/EncodedVideoPlayer.swift
Course/Course/Presentation/Video/YouTubeVideoPlayer.swift

https://github.com/openedx/openedx-app-ios/assets/128456094/9f24bdf3-bb54-4727-a393-4a11ecdeba5e

Video start playing by subtitle taps

---

Course/Course/Data/CourseRepository.swift
Course/Course/Domain/Model/CourseDates.swift
Course/Course/Presentation/Dates/CourseDatesView.swift
Course/CourseTests/Presentation/Unit/CourseDateViewModelTests.swift

This is continuity of https://github.com/openedx/openedx-app-ios/pull/137
to address feedback, as original PR was merged.
This PR also fixes edge case for the Today block and siblings for Today block, small color fixes to Circle and bit of refactoring.

chore: course dates feature

---

Core/Core.xcodeproj/project.pbxproj
config_script/process_config.py

This PR updates `process_config.py` script and updates Google and Microsoft scheme

chore: add google and microsoft scheme 

---

Course/Course/Presentation/Outline/CourseExpandableContentView.swift
Course/Course/Presentation/Unit/CourseUnitView.swift
Course/Course/Presentation/Unit/Subviews/DropdownList/CourseUnitDropDownTitle.swift
Course/Course/Presentation/Unit/Subviews/DropdownList/CourseUnitVerticalsDropdownView.swift
Course/Course/Presentation/Unit/Subviews/DropdownList/DropdownAnimationModifier.swift

* [iOS] Fix section title displayed in two lines #208
* [iOS] Improve arrow animation for section drop-down and sequence nested lists #207
* [iOS] Long section name is partially overlapped by navigation buttons #205
* [iOS] Content page reloads when it is reselected in the drop-down list #204
[![_Simulator Screenshot - iPhone 15 - 2023-12-14 at 16 19 10](https://github.com/touchapp/openedx-app-ios/assets/480059/3a0ebbd0-f1a8-4f33-9615-0618ec54cb7e)](https://github.com/touchapp/openedx-app-ios/assets/480059/9ad9d15f-6b48-4c78-ab81-aa5900ec80cd)
[![_Simulator Screenshot - iPhone 15 - 2023-12-14 at 16 19 12](https://github.com/touchapp/openedx-app-ios/assets/480059/7bcf237e-567b-4e51-92cc-e7a9c426dafd)](https://github.com/touchapp/openedx-app-ios/assets/480059/4e8c4bbf-0fc4-4ccd-87b6-18a8a48f …

arrow animation & fix for section title

---

Core/Core/SwiftGen/Strings.swift
Core/Core/en.lproj/Localizable.strings
Core/Core/uk.lproj/Localizable.strings
Course/Course/Presentation/Container/CourseContainerViewModel.swift
Course/Course/Presentation/Outline/ContinueWithView.swift
Course/Course/Presentation/Outline/CourseOutlineView.swift
Course/Course/SwiftGen/Strings.swift
Course/Course/en.lproj/Localizable.strings
Course/Course/uk.lproj/Localizable.strings

This PR improves the course resume logic and navigates the learner to the last visited component screen. The last visited component is being returned from the server for API `/api/mobile/v1/users/\(userName)/course_status_info/\(courseID)`
Task Link:  [Remove Sequence units level from Resume action](https://github.com/openedx/openedx-app-ios/issues/199)
https://github.com/openedx/openedx-app-ios/assets/5606473/a052d244-d431-4c9b-b601-3ba5bf9e5422

feat: Update course resume logic, navigate learner to last viewed component

---

Course/Course/Presentation/Unit/CourseUnitView.swift

Small fix for https://github.com/openedx/openedx-app-ios/issues/186 bug
In landscape mode, the screen size is not enough to display the "Open in Browser" button if the content has a title. I've placed this "Unknown" view inside a scroll view.
https://github.com/openedx/openedx-app-ios/assets/37253/fde106b8-8a81-4b07-b2d5-b685909feb8c

Open in browser button is partially hidden in landscape mode

---

Documentation/Theming_implementation.md
config_script/whitelabel.py

- Added ability to specify which other targets in the project should receive the new development team ID (other than 'OpenEdX' by default) - this helps avoid build errors when deploying to a device in Xcode
- Added ability to override font in iOS app 
- Updated documentation to reflect the above changes
Clone `https://github.com/edx/edx-mobile-config` into the OpenEdX root folder and switch to the `anton/openedX-theming` branch.
From the OpenEdX root folder, run the script as:
```bash
python config_script/whitelabel.py --config-file=edx-mobile-config/openEdXAssets/whitelabel.yaml -v
```
Install on your simulator or device
All possible config parameters are described in [this documentation](https://github.com/touchapp/openedx-app-ios/blob/theme/script_improvements-/Documentation/Theming_imp …

Theme/script improvements 

---

Core/Core/Extensions/UIApplicationExtension.swift
Core/Core/Extensions/ViewExtension.swift
Core/Core/View/Base/ScrollSlidingTabBar/ScrollSlidingTabBar.swift
Core/Core/View/Base/WebUnitView.swift
Course/Course/Presentation/Container/CourseContainerView.swift
Theme/Theme/Theme.swift

This PR fixes bug with Navigation Bar background and title colors in dark mode. 
By some reason calculated UIColor doesn't work for navigation bar (like `Theme.Colors.textPrimary.uiColor()`) and I added UIColors struct into Theme.
After fix Navigation Bar looks like this:

fix: navigation bar colors

---

Authorization/Authorization/Presentation/Login/SignInView.swift
Authorization/Authorization/Presentation/Registration/SignUpView.swift
Authorization/Authorization/Presentation/Reset Password/ResetPasswordView.swift
Authorization/Authorization/Presentation/SocialAuth/SocialAuthView.swift
Authorization/Authorization/Presentation/Startup/StartupView.swift
Core/Core/View/Base/HTMLFormattedText.swift
Core/Core/View/Base/LogistrationBottomView.swift
Core/Core/View/Base/NavigationBar.swift
Core/Core/View/Base/PickerMenu.swift
Core/Core/View/Base/PickerView.swift
Core/Core/View/Base/RegistrationTextField.swift
WhatsNew/WhatsNew/Presentation/WhatsNewView.swift

This PR sets accessibility identifiers for startup, signin, forgot password and whats new screens. These accessibility identifiers will be used by the QA team to automate the testing flow.

Chore: Set Accessibility Identifiers for Startup, Signin. Register, WhatsNew Screens

---

Authorization/AuthorizationTests/AuthorizationMock.generated.swift
Core/Core/Data/Persistence/CoreDataModel.xcdatamodeld/CoreDataModel.xcdatamodel/contents
Core/Core/Data/Persistence/CorePersistenceProtocol.swift
Core/Core/Network/DownloadManager.swift
Course/Course/Presentation/Container/CourseContainerView.swift
Course/Course/Presentation/Container/CourseContainerViewModel.swift
Course/CourseTests/CourseMock.generated.swift
Course/CourseTests/Presentation/Container/CourseContainerViewModelTests.swift
Dashboard/DashboardTests/DashboardMock.generated.swift
Discovery/DiscoveryTests/DiscoveryMock.generated.swift
Discussion/Discussion/Presentation/DiscussionTopics/DiscussionTopicsView.swift
Discussion/Discussion/Presentation/DiscussionTopics/DiscussionTopicsViewModel.swift
Discussion/DiscussionTests/DiscussionMock.generated.swift
OpenEdX/DI/ScreenAssembly.swift
OpenEdX/Data/CorePersistence.swift
OpenEdX/Router.swift
Profile/Profile/Data/ProfileRepository.swift
Profile/Profile/Presentation/Profile/ProfileView.swift
Profile/Profile/Presentation/Profile/ProfileViewModel.swift
Profile/ProfileTests/Presentation/Profile/ProfileViewModelTests.swift
Profile/ProfileTests/ProfileMock.generated.swift

When a user logs out, the downloaded content should not be deleted, so that when the user logs in again, all downloaded content will be available to him again.
For each user, only their downloaded content should be displayed.

feat: Don't delete downloaded videos when the user logs out

---

Course/Course/Presentation/Video/EncodedVideoPlayer.swift
Course/Course/Presentation/Video/YouTubeVideoPlayerViewModel.swift

This PR is for https://github.com/openedx/openedx-app-ios/issues/305
To avoid confusing users when the default player doesn't show the play button at startup, we've added autoplay.

Auto-play for video and youtube players

---

Documentation/Theming_implementation.md
config_script/whitelabel.py

This small improvement is due to the ability to replace LaunchScreen.storyboard for Theming purposes. (see this [Comment](https://github.com/openedx/openedx-app-ios/pull/311#discussion_r1519518829) for more info)
Added ability to replace any files in project folders. 
Updated [Documentation](https://github.com/edx/edx-mobile-marketplace-ios/blob/import-files-for-theming/Documentation/Theming_implementation.md).

Import files for theming

---

Documentation/APIs_Compatibility.md
README.md

EducationX name and URL replaced with Open edX

docs: Update README

---

Core/Core/View/Base/StyledButton.swift
Profile/Profile/Presentation/DeleteAccount/DeleteAccountView.swift
Theme/Theme/Theme.swift

Fix for [325 Issue](https://github.com/openedx/openedx-app-ios/issues/315)
As @sdaitzman suggested, the "Back to Profile" button uses the basic button style. The "Delete Account" button uses the red error/danger colour to highlight which action is destructive.
Also, `StyledButton View` can now have an `icon` image. The icon can be placed to the `left` or `right` of the button title text.
Light|Dark
--|--
Light|Dark
--|--

Fix for the alignment of the "Back to profile" button

---

docs/0001-strategy-for-maintaining-OS-versions.rst

Fix the RST preview on GitHub.
Preview link:
- https://github.com/Zeit-Labs/openedx-app-ios-contrib/blob/reformat-0001/docs/0001-strategy-for-maintaining-OS-versions.rst

docs: reformat 0001-strategy-for-maintaining-OS-versions.rst

---

docs/0002-atlas-translations-management.rst

Please review this proposal. We're set to start on April 1st, 2024.
Please let us know if you have any questions or objections.
I've omitted many [OEP-58](https://docs.openedx.org/en/latest/developers/concepts/oep58.html) related details, to keep the discussion focused on the mobile parts.
Preview link the proposal doc:
- https://github.com/Zeit-Labs/openedx-app-ios-contrib/blob/atlas/docs/0002-atlas-translations-management.rst
This pull request is part of the [FC-0055 project](https://openedx.atlassian.net/l/cp/nSkaHb7G) which implements the [Translation Infrastructure update OEP-58](https://docs.openedx.org/en/latest/developers/concepts/oep58.html) for mobile apps.

docs: design for atlas pull and translations management | FC-0055

---

OpenEdX/Managers/DeepLinkManager/DeepLinkManager.swift
OpenEdX/Managers/DeepLinkManager/DeepLinkRouter/DeepLinkRouter.swift

[LEARNER-9888](https://2u-internal.atlassian.net/browse/LEARNER-9888): Navigate to a particular course component upon tapping the link from the native calendar application synced with the calendar for that specific course.
**Demo:**
https://github.com/openedx/openedx-app-ios/assets/11990137/d83276a7-98a3-4bb9-80e1-d6e0e0cd688e

feat: Calendar deep link to course component

---

OpenEdX/Router.swift

The test value[ in this PR](https://github.com/openedx/openedx-app-ios/commit/3531fc2#diff-2b25a8034888f1572195662d18b46ec140dd9b62b15ea2f9710bdf8f7a7d63f8L135) was erroneously merged into develop

fix: rolled back test value

---

Authorization/Authorization/Presentation/Login/SignInView.swift
Authorization/Authorization/Presentation/Registration/SignUpView.swift
Authorization/Authorization/Presentation/Startup/StartupView.swift
Authorization/Authorization/SwiftGen/Strings.swift
Authorization/Authorization/en.lproj/Localizable.strings
Authorization/Authorization/uk.lproj/Localizable.strings
Core/Core.xcodeproj/project.pbxproj
Core/Core/Extensions/ViewExtension.swift
Core/Core/View/Base/BackNavigationButton.swift
Core/Core/View/Base/BackNavigationButtonViewModel.swift
Core/Core/View/Base/NavigationBar.swift
Discovery/Discovery/Presentation/NativeDiscovery/SearchView.swift
Discussion/Discussion/Presentation/Comments/Responses/ResponsesView.swift
Discussion/Discussion/Presentation/Comments/Thread/ThreadView.swift
Discussion/Discussion/Presentation/DiscussionTopics/DiscussionSearchTopicsView.swift
OpenEdX/DI/ScreenAssembly.swift
OpenEdX/Router.swift
Profile/Profile/Presentation/DeleteAccount/DeleteAccountView.swift
Profile/Profile/Presentation/EditProfile/EditProfileView.swift

Related to [iOS] Add long tap and menu for custom navbar #382
Before|After
--|--
<details>
<summary>Videos</summary>
https://github.com/openedx/openedx-app-ios/assets/480059/60a7849e-0607-4a69-90d7-0d163f75a7bc
https://github.com/openedx/openedx-app-ios/assets/480059/7cf56644-3aac-4c05-b515-f3dfe5ba7d61  
</details>

[iOS] Add long tap and menu for custom navbar

---

catalog-info.yaml

Adding `catalog-info.yaml` according to [OEP-55](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055-proc-project-maintainers.html).

chore: add maintainership documentation

---

Core/Core/Extensions/DateExtension.swift

[LEARNER-9936](https://2u-internal.atlassian.net/browse/LEARNER-9936): iOS - Maintain calendar toggle and local calendar event mapping
In this pull request, we tackled the following two issues:
- Resolved an outdated calendar alert while upgrading the production application to the new application.
- Corrected the display of identical date calendar events appearing in two sections due to nanosecond disparities.
Screenshots highlight these discrepancies.
| Before | After |
|----------|----------|
| ![Simulator Screenshot - iPhone 15 - 2024-04-19 at 19 54 47](https://github.com/openedx/openedx-app-ios/assets/11990137/af1d7582-a187-4f47-9e23-3b55ec9aa70f) | ![Simulator Screenshot - iPhone 15 - 2024-04-19 at 19 53 49](https://github.com/openedx/openedx-app-ios/assets/11990137/34e9f280-375e-458e …

fix: Maintain calendar toggle and local calendar event mapping

---

Course/Course/Presentation/Subviews/CourseVideoDownloadBarView/CourseVideoDownloadBarViewModel.swift

That PR fixes bug with wrong download switch state in Videos tab:
https://github.com/openedx/openedx-app-ios/assets/480059/08aba5ef-1bb8-499e-ae1d-d86b00518922

Fix wrong download state

---

Core/Core/View/Base/ScrollSlidingTabBar/ScrollSlidingTabBar.swift
Theme/Theme/Assets.xcassets/Colors/SlidingTabBar/slidingSelectedTextColor.colorset/Contents.json
Theme/Theme/SwiftGen/ThemeAssets.swift
Theme/Theme/Theme.swift

This PR enhances the course menu bar theming capability by introducing a new color for selected option.
Note: It won't affect open edX theme.

chore: Sliding course menu theme enhancement

---

Core/Core/Configuration/Config/DiscoveryConfig.swift

Fixed discovery configuration to enable it by default for the Open edX app.

fix: discovery enabled by default

---

.swiftlint.yml
Authorization/Authorization/Presentation/AuthorizationAnalytics.swift
Core/Core/Extensions/DateExtension.swift
Core/Core/Extensions/Dictionary+JSON.swift
Core/Core/Extensions/String+JSON.swift
Core/Core/Extensions/ViewExtension.swift
Core/Core/Network/DownloadManager.swift
Core/Core/Providers/SocialAuth/MicrosoftAuthProvider.swift
Core/Core/View/Base/AppReview/ThirdPartyMailer/ThirdPartyMailClient.swift
Core/Core/View/Base/RefreshableScrollView.swift
Core/Core/View/Base/UnitButtonView.swift
Core/Core/View/Base/Webview/WebView.swift
Course/Course.xcodeproj/project.pbxproj
Course/Course/Presentation/Dates/CourseDatesView.swift
Course/Course/Presentation/Outline/CourseOutlineView.swift
Course/Course/Presentation/Unit/CourseNavigationView.swift
Course/Course/Presentation/Video/SubtittlesView.swift
Course/Course/Presentation/Video/YouTubeVideoPlayer.swift
Discussion/Discussion/Data/Network/DiscussionRepository.swift
Discussion/Discussion/Domain/Model/UserThread.swift
Discussion/Discussion/Presentation/DiscussionTopics/DiscussionSearchTopicsViewModel.swift
OpenEdX/Managers/AnalyticsManager/AnalyticsManager.swift
OpenEdX/Managers/PushNotificationsManager/Listeners/BrazeListener.swift
Podfile
Podfile.lock
Profile/Profile/Presentation/EditProfile/EditProfileViewModel.swift
Theme/Theme/Theme.swift

This pull request updates the Swiftlint version and addresses a bunch of warnings. 
| Before | After |
|----------|----------|
| <img width="64" alt="Screenshot 2024-05-09 at 11 31 39" src="https://github.com/openedx/openedx-app-ios/assets/127732735/b136f6a7-9107-485a-adc0-d46f7bd7edfd"> | <img width="64" alt="Screenshot 2024-05-09 at 11 34 38" src="https://github.com/openedx/openedx-app-ios/assets/127732735/5666e110-216e-4a81-983a-e6cab2f9cd9a"> |
Fixed:
- Trailing Whitespace Violation
- Line Length Violation
- Generated and third-party files excluded from linting

fix: build warnings

---

Core/Core/Assets.xcassets/arrowLeft.imageset/Contents.json

I'm Rawan Matar, from ZeitLabs.
I start working on supporting RTL in OpenEdx iOS app, and this is the first change in my plan.
changed the direction attribute of the "arrowLeft" image in Core/Assets.
| Before | After |
|--------|-------|
| ![IMG_3090](https://github.com/openedx/openedx-app-ios/assets/41669180/a1bbc540-d9d2-426f-871a-bb6b1f49d3b6)| ![IMG_3087](https://github.com/openedx/openedx-app-ios/assets/41669180/3a25a23b-3e44-4e06-9b84-b278cd1f8735)|

fix: RTL arrowLeft in core assets

---

Core/Core/Network/AuthEndpoint.swift
Course/Course/Presentation/Video/PlayerViewControllerHolder.swift
Course/Course/Presentation/Video/YoutubePlayerViewControllerHolder.swift
Dashboard/Dashboard/Presentation/Elements/CategoryFilterView.swift
Dashboard/Dashboard/Presentation/Elements/PrimaryCardView.swift
Profile/Profile/Data/Network/ProfileEndpoint.swift

This PR address small issues with API paths and errors while creating archive.
1. Path issues:
Some API paths are starting without the `/`. Ideally it should work and it works sometimes because of `appendingPathComponent`.  But most of the time, it fails and path becomes `HostURLAPIPath` instead of `HostURL/APIPath`. Added the `/` to the API paths where it was missing.
2. Archive issue:
Some mock code was without the `#if DEBUG` and it was throughing an error while creating an archive. 
3. Theme
Some changes to fix the edX theme. These changes will not impact the openedX theme.

fix: APIs path and archive fix

---

Core/Core/Network/DownloadManager.swift

This is small fix for issue https://github.com/openedx/openedx-app-ios/issues/451
For some reason we deleted the data from DB first and then tried to delete the local file, but the url of the file is built on the data from DB. Now it's fixed

Small fix for deleting downloaded files

---

Authorization/AuthorizationTests/AuthorizationMock.generated.swift
Core/Core/Data/CoreStorage.swift
Core/Core/Network/DownloadManager.swift
Course/CourseTests/CourseMock.generated.swift
Dashboard/DashboardTests/DashboardMock.generated.swift
Discovery/DiscoveryTests/DiscoveryMock.generated.swift
Discussion/DiscussionTests/DiscussionMock.generated.swift
OpenEdX/Data/AppStorage.swift
OpenEdX/RouteController.swift
Profile/ProfileTests/ProfileMock.generated.swift

[LEARNER-9966](https://2u-internal.atlassian.net/browse/LEARNER-9966): Delete old downloaded videos data on device to optimize storage
We decided not to migrate downloaded content but have to look into deleting the old downloaded videos so the app does not create useless dummy data in the learners' devices.
**Technical Details:**
The old application saves users' downloaded videos in the `Application Support` directory within folders named users' MD5 hashes. When multiple users log into the same device, separate MD5 hashed folders are created for each user, each containing that user's downloaded data.
After upgrading the application, we can use the MD5 hash algorithm to delete only the data of the currently logged-in user, while the data for other users will remain intact. Because MD5 hash …

feat: Delete old downloaded videos data on device to optimize storage

---

.gitignore
Makefile
README.md
i18n_scripts/requirements.txt
i18n_scripts/translation.py

This pull request provides the CI scripts and developer tooling for the [Atlas Translations Management Design
](https://github.com/openedx/openedx-app-ios/blob/develop/docs/0002-atlas-translations-management.rst) proposal related to [OEP-58](https://docs.openedx.org/en/latest/developers/concepts/oep58.html).
```
make ATLAS_OPTIONS='--repository=Zeit-Labs/openedx-translations --revision=fc_55_sample' pull_translations
```
1) The None-English translations will be pulled from openedx-translations repo into `I18N/` directory.
2) Then each language file will be split and distributed to the modules one by one
3) In the end, the pulled translations will be removed and only the split translations can be found in the modules' directories
1) The above command should not produce errors when …

feat: atlas pull and push scripts | FC-55

---

Core/Core/View/Base/VideoDownloadQualityView.swift
Course/Course/Presentation/Outline/CourseOutlineView.swift
Course/Course/Presentation/Subviews/VideoDownloadQualityBarView/VideoDownloadQualityContainerView.swift

This PR is the fix for https://github.com/openedx/openedx-app-ios/issues/436
In a modal view, the modal representation of that view should be used.
Added `isModal` parameter with a default value of `false`, which determines which presentation will be used.
The full screen view  in the Settings does not change.
Now | After fix
--- | ---

Fix video quality settings in modal representation

---

Course/Course/Presentation/Subviews/CourseVideoDownloadBarView/CourseVideoDownloadBarViewModel.swift
Course/Course/Presentation/Subviews/CustomDisclosureGroup.swift
Course/Course/SwiftGen/Strings.swift
Course/Course/en.lproj/Localizable.strings
Course/Course/uk.lproj/Localizable.strings

[iOS] Prompt | Confirmation Alert Missing Before Deleting Section-Level Downloaded Videos #456

[iOS] Prompt | Confirmation Alert Missing Before Deleting Section-Level Downloaded Videos #456

---

Authorization/Authorization/Presentation/Login/SignInViewModel.swift
Authorization/Authorization/Presentation/Registration/SignUpViewModel.swift
Core/Core/Data/CoreStorage.swift
Core/Core/Extensions/Notification.swift
Core/Core/Network/RequestInterceptor.swift
Dashboard/Dashboard/Presentation/ListDashboardViewModel.swift
Dashboard/Dashboard/Presentation/PrimaryCourseDashboardViewModel.swift
Discussion/Discussion/Data/Model/Data_CommentsResponse.swift
Discussion/Discussion/Data/Network/DiscussionEndpoint.swift
Discussion/Discussion/Data/Network/DiscussionRepository.swift
OpenEdX.xcodeproj/project.pbxproj
OpenEdX/AppDelegate.swift
OpenEdX/DI/AppAssembly.swift
OpenEdX/Data/AppStorage.swift
OpenEdX/Data/Network/NotificationsEndpoints.swift
OpenEdX/Managers/DeepLinkManager/DeepLinkManager.swift
OpenEdX/Managers/DeepLinkManager/DeepLinkRouter/DeepLinkRouter.swift
OpenEdX/Managers/DeepLinkManager/Link/DeepLink.swift
OpenEdX/Managers/FirebaseAnalyticsService/FirebaseAnalyticsService.swift
OpenEdX/Managers/PushNotificationsManager/Listeners/BrazeListener.swift
OpenEdX/Managers/PushNotificationsManager/Listeners/FCMListener.swift
OpenEdX/Managers/PushNotificationsManager/Providers/BrazeProvider.swift
OpenEdX/Managers/PushNotificationsManager/Providers/FCMProvider.swift
OpenEdX/Managers/PushNotificationsManager/PushNotificationsManager.swift
OpenEdX/Router.swift
Profile/Profile/Presentation/Settings/SettingsViewModel.swift

This pull request introduces Firebase Cloud Messaging (FCM) to the project, enabling the functionality for receiving push notifications from Firebase.
Testing:
• Verified push notifications are received when the app is in the foreground, background, and terminated states.
• Confirmed the app correctly handles notification taps and displays relevant content.
• Ensured token generation and handling work as expected, including handling token refreshes.
Please use the Firebase console for testing; here is a set of all the required fields for navigation:
Notifications:
1. User has been enrolled
notification_type: `enroll`
course_id: Your course ID (example: course-v1:future+f1+2024)
2. User has been unenrolled
notification_type: `unenroll`
3. User has been added as a beta tester …

feat: [FC-0047] FCM

---

OpenEdX/DI/AppAssembly.swift
OpenEdX/Managers/PushNotificationsManager/Listeners/BrazeListener.swift
OpenEdX/Managers/PushNotificationsManager/Providers/BrazeProvider.swift
OpenEdX/Managers/PushNotificationsManager/PushNotificationsManager.swift

This PR fixes the issue with push notifications.
Issue details: https://github.com/openedx/openedx-app-ios/issues/472

chore: fix double notification routing and segment callback

---

Dashboard/Dashboard/Presentation/ListDashboardView.swift

This PR fixes issue https://github.com/openedx/openedx-app-ios/issues/468 where Settings button is missed for Dashboard type "list"
After fix:
iPhone | iPad
--- | ---

Settings button for dashboard type 'list'

---

Core/Core/Extensions/UIApplicationExtension.swift
Core/Core/View/Base/DynamicOffsetView.swift
Course/Course/Presentation/Container/CourseContainerView.swift

[iOS] UI issues on iPhone SE #481
- Fixed bug with status empty status bar on SE device
- Fixed overlap bug

[iOS] UI issues on iPhone SE

---

Core/Core/View/Base/PickerMenu.swift

this PR fix crash when after filter applying `PickerView` crash with `index out of bounds` error.
It's crashing on scrolling while the picker is empty (e.g you search abcdef in country picker and try to scroll the empty picker)
https://github.com/user-attachments/assets/2e88f288-bd34-4472-8252-a120fdf35326

fix: picker crash when no elements

---

Core/Core/View/Base/Webview/WebView.swift

This PR fixes the following iPad Crash. Although I couldn't reproduce the crash in the actual case, the crash happened when I ran the same code by clicking a button.

fix: fix iPad crash of alert controller

---

Course/Course/Data/CourseRepository.swift
Course/Course/Domain/CourseInteractor.swift
Course/Course/Presentation/Video/PlayerTrackerProtocol.swift
Course/Course/Presentation/Video/VideoPlayerViewModel.swift

App was crashing in two cases of videos, both the crashes can be tested on course `Project Management for Development`
1. When the LMS is returning an empty URL for video encoding
How it can be tested: 
It can be tested on the first section, `Start here` -> `0.1 Welcome to the course` -> going to the video
Solution: 
Mimic the behaviour from the old app.
2. When the LMS returns wrong data for transcripts, LSM is returning less time for endtime than the starttime of the transcript.
How it can be tested: 
1. Go to Videos tab
2. Go to Module 1: Project Chapter 
3. Go to 1.1.5 Video: Project Chapter (can be selected from the dropdown switcher)
4. Go to the video component

fix: video crashes

---

OpenEdX/Data/DashboardPersistence.swift

This PR fixes the crash with coredata. Although, I'm not able to reproduce the crash  but from dry run it it can occur because of deleting the data async and right before saving new data and expecting the data will be deleted. 
Crash Link: https://console.firebase.google.com/u/1/project/openedx-mobile/crashlytics/app/ios:org.edx.mobile/issues/cb09ae273338d6fa32acb9f64effefbf?time=last-seven-days&types=crash&versions=6.0.0%20(2)&sessionEventKey=f4c972ede3fd4c18901af18a71e6b702_1979319760445579771

fix: fix coredata crash on primary course

---

Core/Core/SwiftGen/Strings.swift
Core/Core/View/Base/BackNavigationButton.swift
Core/Core/View/Base/OfflineSnackBarView.swift
Core/Core/View/Base/UnitButtonView.swift
Core/Core/View/Base/Webview/WebView.swift
Core/Core/en.lproj/Localizable.strings
Dashboard/Dashboard/Data/Network/DashboardEndpoint.swift
Profile/Profile/Presentation/Settings/SettingsView.swift
Profile/Profile/SwiftGen/Strings.swift
Profile/Profile/en.lproj/Localizable.strings

This batch contains next fixes:
1. Fix Initial Accessibility Testing Issues
(organized some accessibility labels and moved ‘Dates & Calendar’ into localization)
https://github.com/edx/edx-mobile-marketplace-ios/pull/29
2. Update offline bar style https://github.com/edx/edx-mobile-marketplace-ios/pull/34 
3. Open link in Safari if link has target=”blank” - fix some links opening
https://github.com/edx/edx-mobile-marketplace-ios/pull/31
4. Fix All Courses Taping Issue - filters “All”, “In progress” etc work buggy
https://github.com/edx/edx-mobile-marketplace-ios/pull/36
all changes are approved by @marcotuts in [this document](https://docs.google.com/document/d/1QoY8c2eX17n-O9AfpjNfCpgBf_75qNCXMebpKz1fYiQ/edit?tab=t.0)

fix: Part 2 sync to upstream

---

Core/Core.xcodeproj/project.pbxproj
Course/Course/Presentation/Unit/Subviews/NotAvailableOnMobileView.swift

This PR fixes an application startup crash on application startup
Downgrading the Facebook SDK version solves the problem

fix: The latest facebook sdk issue

---

Authorization/Authorization/Presentation/Base/FieldsView.swift
Authorization/Authorization/Presentation/Login/SignInView.swift
Core/Core.xcodeproj/project.pbxproj
Core/Core/View/Base/AlertView.swift
Core/Core/View/Base/RegistrationTextField.swift
Core/Core/View/Base/SecureInputView.swift
Course/Course/Presentation/Subviews/CourseVideoDownloadBarView/CourseVideoDownloadBarView.swift
Course/Course/Presentation/Subviews/CourseVideoDownloadBarView/CourseVideoDownloadBarViewModel.swift
Dashboard/Dashboard/Presentation/AllCoursesView.swift
OpenEdX/Data/AppStorage.swift

This sync PR contains next fixes:
1. Add eye icon for password field https://github.com/edx/edx-mobile-marketplace-ios/pull/42
2. Clear cookies by logout to fix Register experience https://github.com/edx/edx-mobile-marketplace-ios/pull/44
3. UI fix: reduce grid spacing https://github.com/edx/edx-mobile-marketplace-ios/pull/47
4. UI fix for Alert’s Title truncation https://github.com/edx/edx-mobile-marketplace-ios/pull/53
5. Videos Tab: Show downloading video size in Mb or Gb https://github.com/edx/edx-mobile-marketplace-ios/pull/57
6. Remove urls from headings of End User license agreements https://github.com/edx/edx-mobile-marketplace-ios/pull/65

fix: Part 5 sync to upstream

---

config_script/whitelabel.py

Fix whitelabel script execution after commenting out Fullstory function - added `pass` into empty `if`
Without this script produces error:
```
File ".../config_script/whitelabel.py", line 572
else:
^
IndentationError: expected an indented block after 'if' statement on line 569
... % python3 config_script/whitelabel.py --config-file=../edx-mobile-config/openEdXAssets/whitelabel.yaml
```
Also updated regex to find the development team in the project file, as it could be empty

fix: Quick fix whitelabel script error

---

Authorization/Authorization/Presentation/Startup/StartupView.swift
Authorization/Authorization/Presentation/Startup/StartupViewModel.swift
Core/Core/View/Base/LogistrationBottomView.swift
Discovery/Discovery/Presentation/NativeDiscovery/CourseDetailsView.swift
Discovery/Discovery/Presentation/NativeDiscovery/DiscoveryView.swift
Discovery/Discovery/Presentation/WebDiscovery/DiscoveryWebview.swift
OpenEdX/DI/ScreenAssembly.swift

On Logistration Bottom View did not check if SSO was enabled or not. Because of this, the ‘Sign in with SSO’ button was displayed in the start view even with SSO disabled:

chore: added SSO switch-on check 

---

Core/Core/View/Base/SecureInputView.swift

Disabled autocapitalisation for TextField for password hide/unhide function.

chore: disabled autocapitalization for TextField

---

Authorization/Authorization/Presentation/AuthorizationAnalytics.swift
Authorization/Authorization/Presentation/Login/SignInViewModel.swift
Authorization/Authorization/Presentation/Registration/SignUpViewModel.swift
Authorization/Authorization/Presentation/SSO/SSOWebViewModel.swift
Authorization/Authorization/Presentation/SocialAuth/SocialAuthViewModel.swift
Authorization/AuthorizationTests/AuthorizationMock.generated.swift
Authorization/AuthorizationTests/Presentation/Login/SignInViewModelTests.swift
Authorization/AuthorizationTests/Presentation/Register/SignUpViewModelTests.swift
Core/Core/Configuration/BaseRouter.swift
Core/Core/View/Base/LogistrationBottomView.swift
Core/CoreTests/CoreMock.generated.swift
Course/CourseTests/CourseMock.generated.swift
Dashboard/DashboardTests/DashboardMock.generated.swift
Discovery/DiscoveryTests/DiscoveryMock.generated.swift
Discussion/DiscussionTests/DiscussionMock.generated.swift
OpenEdX/DI/ScreenAssembly.swift
OpenEdX/RouteController.swift
OpenEdX/Router.swift
OpenEdX/View/MainScreenViewModel.swift
Profile/ProfileTests/ProfileMock.generated.swift
WhatsNew/WhatsNew/Presentation/WhatsNewView.swift
WhatsNew/WhatsNew/Presentation/WhatsNewViewModel.swift

This PR comes from https://github.com/edx/edx-mobile-marketplace-ios/pull/106 and fixes the display of the Social Auth Banner when What's new View is enabled. Prior to the fix, we were losing the Social Auth Banner because it was implemented with a `.userAuthorised` notification, which never happens for MainScreenViewModel

Fix: Social auth banner 

---

Core/Core/Domain/Model/CourseBlockModel.swift
Core/CoreTests/DownloadManager/DownloadManagerTests.swift
Course/Course/Data/CourseRepository.swift
Course/Course/Presentation/Unit/CourseUnitViewModel.swift
Course/CourseTests/Presentation/Container/CourseContainerViewModelTests.swift

This PR is originated from https://github.com/edx/edx-mobile-marketplace-ios/pull/89 and improves the logic of streaming videos:
- If the auto preference is selected in settings for streaming videos, then the server returned stream_priority is used to pick the URL for streaming.
- If any other preference is selected for streaming videos, then the predefined (hardcoded in codebase list) is used to pick the URL for streaming.

Sync: video stream priority

---

Course/CourseTests/Presentation/Container/CourseDownloadHelperTests.swift

Fix the missed parameter in the CourseDownloadHelperTests.

fix: course download helper tests

---

Discovery/Discovery/Presentation/NativeDiscovery/DiscoveryView.swift

feat: fix sign in position on discovery view

---

ci_scripts/ci_prepare_env.sh

Fixes CI failure by removing the explicit installation of the `xcodes` package via Homebrew. The macOS runner already includes `xcodes`, and the manual installation was causing conflicts with the pre-installed version.

build: fix workflow issues
