openedx/openedx-app-ios

Discussion/Discussion/Data/Network/DiscussionEndpoint.swift, Discussion/Discussion/Data/Network/DiscussionRepository.swift, Discussion/Discussion/Domain/DiscussionInteractor.swift, Discussion/Discussion/Domain/Model/ThreadType.swift, Discussion/Discussion/Domain/Model/UserThread.swift, Discussion/Discussion/Presentation/Comments/Base/BaseResponsesViewModel.swift, Discussion/Discussion/Presentation/Comments/Thread/ThreadView.swift, Discussion/Discussion/Presentation/Comments/Thread/ThreadViewModel.swift, Discussion/Discussion/Presentation/DiscussionTopics/DiscussionSearchTopicsViewModel.swift, Discussion/Discussion/Presentation/Posts/PostState.swift, Discussion/Discussion/Presentation/Posts/PostsView.swift, Discussion/Discussion/Presentation/Posts/PostsViewModel.swift
=> fix states logic on Discussions PostsView

Course/Course/Presentation/Container/CourseContainerViewModel.swift
Fix downloading files only from selected Sequential
=> Fix downloading CourseSequential blocks

Core/Core/Domain/Model/CourseDetailBlock.swift
change the unit button on the course vertical
=> change the unit button

Course/Course/Presentation/Details/CourseDetailsView.swift
fix the "enroll to course" button position on the iPad
=> fix button position on CourseDetailsView for iPad

Discussion/Discussion/Presentation/Comments/Thread/ThreadViewModel.swift
fix discussion feature pagination issue
=> bugfix discussion

Course/Course/Data/CourseRepository.swift
Fix course repository mock translate in courseStructureJson
=> fix translate

Course/Course/Presentation/Handouts/HandoutsView.swift
disable routing whenever handouts are empty
=> Empty handouts bug

Core/Core/Configuration/Connectivity.swift, Course/Course/Presentation/Video/PlayerViewController.swift
Fix the isMobileData variable in the Connectivity module.
Add the possibility to play videos with sound in silent mode.
=> Silent mode in Video and Connectivity issue

Core/Core/Assets.xcassets/Profile/done.imageset/Contents.json, Core/Core/Assets.xcassets/arrowLeft.imageset/Contents.json, Core/Core/Assets.xcassets/arrowRight16.imageset/Contents.json, Core/Core/Extensions/UIApplicationExtension.swift, Core/Core/View/Base/StyledButton.swift, Core/Core/View/Base/WebView.swift, Course/Course/Data/CourseRepository.swift, Course/Course/Data/Network/CourseDetailsEndpoint.swift, Dashboard/Dashboard/Presentation/DashboardViewModel.swift
Change CourseDetailsEndpoint to CourseEndpoint
Fix the incorrect back button on the course screen
Fix the issue on the Delete account view. The inactive button is clickable.
=> September bugfixes

Core/Core/Extensions/DateExtension.swift, Course/Course/Presentation/Video/EncodedVideoPlayer.swift, Course/Course/Presentation/Video/SubtittlesView.swift, Course/Course/Presentation/Video/YouTubeVideoPlayer.swift, Course/Course/Presentation/Video/YouTubeVideoPlayerViewModel.swift
Display of video transcripts with active sentence highlighting. Tapping on transcript sentences to navigate to the corresponding part of the video. Mechanism to quickly return to the current active sentence after scrolling.
https://github.com/openedx/openedx-app-ios/assets/128456094/b2cf1f49-e23b-42dd-a9b0-0ddac26bda59
=> Transcript navigation

Profile/Profile/Presentation/Profile/UserProfile/UserProfileView.swift
fix background issue on UserProfileView for dark theme
=> Fix UserProfileView background

Core/Core/View/Base/Webview/WebView.swift
fix for https://github.com/openedx/openedx-app-ios/issues/220
Added a custom user agent for webView to hide the application banner on a web page
=> Add custom user agent to hide app banner on web page

Core/Core.xcodeproj/project.pbxproj, Core/Core/View/Base/WebUnitViewModel.swift, Core/Core/View/Base/Webview/WebviewCookiesUpdateProtocol.swift, Discovery/Discovery/Presentation/WebPrograms/ProgramWebviewView.swift, Discovery/Discovery/Presentation/WebPrograms/ProgramWebviewViewModel.swift, OpenEdX/DI/ScreenAssembly.swift
This PR adds functionality of refresh cookies to programs webview.
[Data for Programs tab isn't displayed](https://github.com/openedx/openedx-app-ios/issues/275)
=> chore: cookies refresh in enrolled programs webview

config_script/whitelabel.py
Small fix to prevent errors in whitelabel python script
=> Whitelabel script small fix

Profile/Profile/Presentation/EditProfile/ProfileBottomSheet.swift
[iOS] UI artifact on iPad Pro 12.9-inch #317
=> fix: UI artifact on iPad Pro 12.9-inch

Core/Core/View/Base/Webview/WebView.swift
[iOS] Unable to open any item from "Bachelor’s Degrees" section in Discover tab #343
=> [iOS] Unable to open any item from "Bachelor’s Degrees" section in Discover tab #343

Course/Course/Presentation/Video/EncodedVideoPlayer.swift
Related to: [iOS] UI issue with top margin on content page on iPad #335
=> [iOS] UI issue with top margin on content page on iPad #335

Core/Core.xcodeproj/project.pbxproj, Course/Course/Presentation/Video/YouTubeVideoPlayer.swift, Course/Course/Presentation/Video/YouTubeVideoPlayerViewModel.swift
Getting the latest version of the YouTubePlayerKit package causes compilation errors . This PR fixes this problem.
=> Update youtube player package version to 1.8.0

catalog-info.yaml
This makes the repository discoverable by the
release repo-tools.
=> chore: add openedx.org/release annotation

Core/Core/Data/Model/Data_PrimaryEnrollment.swift
It's fix for https://github.com/openedx/openedx-app-ios/issues/491 bug
=> fix: BugFix for PrimaryEnrollment data

.github/workflows/unit_tests.yml
Issue: https://github.com/openedx/openedx-app-ios/issues/539
=> build: update action versions

Core/Core/View/Base/OfflineSnackBarView.swift
This PR reverts changes with colours for the Offline Panel that were made to the codebase during the merge https://github.com/edx/edx-mobile-marketplace-ios/pull/34
=> fix: Quick Fix colors for Offline Panel

Core/Core/Analytics/CoreAnalytics.swift, OpenEdX/Managers/AnalyticsManager/AnalyticsManager.swift, OpenEdX/Managers/AnalyticsManager/MainScreenAnalytics.swift, OpenEdX/View/MainScreenViewModel.swift
This PR adds analytics tracking for Push Notifications Permissions status.
Originated from https://github.com/edx/edx-mobile-marketplace-ios/pull/102
=> Push notifications status analytic
